[package]
name = "totallysecurejournal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.18", features = ["env", "derive"] }
jalali-date = "=0.2.0"
shellexpand = "3.1.0"
time = "0.3.36"
